### ISSUE TITLE
blog post image

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#432]

**Comment by guylepage3** [comment]
@shea256 @muneeb-ali, here's the image

![blog-blockstack-pbc](https://user-images.githubusercontent.com/1711854/30608360-102497c6-9d46-11e7-8e5c-9e44b7558737.png)

**Comment by pstan26** [comment]
Could be cool to insert some sense of "global benefit for all humankind" with this announcement, since it goes beyond just documents themselves. Perhaps we place a globe icon behind the docs icon? 

Also for the text, what do you think of changing it to say "Transitioning to a Public Benefit Corporation" so it shows what is happening?

**Comment by guylepage3** [comment]
![blog-blockstack-pbc](https://user-images.githubusercontent.com/1711854/30608845-a01c525a-9d47-11e7-8d61-1842071c91a4.png)

**Comment by guylepage3** [comment]
![blog-blockstack-pbc2](https://user-images.githubusercontent.com/1711854/30609763-42caf234-9d4a-11e7-837d-fecec91c790b.png)
![blog-blockstack-pbc3](https://user-images.githubusercontent.com/1711854/30609764-42d040a4-9d4a-11e7-9be7-b73127192544.png)

**Comment by guylepage3** [comment]
@shea256 @muneeb-ali @kantai @jcnelson @pstan26 Let's go with this image.. Stay clear of BP..

![blog-blockstack-pbc3](https://user-images.githubusercontent.com/1711854/30609764-42d040a4-9d4a-11e7-9be7-b73127192544.png)

**Comment by guylepage3** [comment]
![blog-blockstack-pbc4](https://user-images.githubusercontent.com/1711854/30660582-5c820602-9e0f-11e7-8265-6d619d9afba4.png)
