### ISSUE TITLE
Design new token pricing section on blockstack.com

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#569]
[#380: add a home page section for token pricing](https://github.com/blockstackinc/blockstack-dot-com/issues/380)

**Comment by guylepage3** [comment]
Thinking of executing this design style as it fits well into our isometric illustration style.

![image](https://user-images.githubusercontent.com/1711854/32610343-7c8c8a7e-c530-11e7-8285-b83cf203a2d4.png)
Ref. https://www.pinterest.com/pin/566327721868823674/

**Comment by guylepage3** [comment]
![blockstack-v4 5 0-token-market-cap 2x](https://user-images.githubusercontent.com/1711854/32625886-91e0eb74-c55b-11e7-875b-ca7f511df254.png)

**Comment by tracedwax** [comment]
@guylepage3 👍

**Comment by pstan26** [comment]
Only problem with this is investors can't actually read graph at an angle. *Highly* suggest avoiding angles if that was being considered.
![](https://user-images.githubusercontent.com/1711854/32610343-7c8c8a7e-c530-11e7-8285-b83cf203a2d4.png)


For this graph there is not enough info on what is being shown. Would suggest "Market cap over time given $0.10 price" or something like that, otherwise its confusing.
![](https://user-images.githubusercontent.com/1711854/32625886-91e0eb74-c55b-11e7-875b-ca7f511df254.png)

**Comment by guylepage3** [comment]
@pstan26 we're using the blue graph..

**Comment by pstan26** [comment]
Sure, just wanted to make sure its not at an angle where you can't read the data in it and has descriptive graph title. Looks like it will be beautiful and useful if so.

**Comment by guylepage3** [comment]
yeah.. reading the data would be imperative. was just a low res image i grabbed from the interwebs.

**Comment by guylepage3** [comment]
![10yr-price-chart](https://user-images.githubusercontent.com/1711854/32639707-1bab1adc-c593-11e7-8b47-d82b1473ac3d.png)
