### ISSUE TITLE
Multi-player storage blog post image

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#613]
Started by @yknl 
![image](https://user-images.githubusercontent.com/1711854/35353792-528e493e-0116-11e8-9927-069377948c4c.png)
https://github.com/blockstack/designs/blob/develop/blog/blog-multi-player-storage.sketch

**Comment by guylepage3** [comment]
![blog-multi-player-storage](https://user-images.githubusercontent.com/1711854/35356691-2388b2d8-011f-11e8-8c96-afd4fd2dd5df.png)

**Comment by yknl** [comment]
Looks great! Thanks @guylepage3

**Comment by guylepage3** [comment]
@pstan26 @yknl here's the new image..

**Comment by pstan26** [comment]
Wait what about having a person at the center like we discussed? That way we avoid the idea that this looks like a centralized thing?

**Comment by yknl** [comment]
That's true, without a person in the middle it is actually starting to look like centralization.

**Comment by guylepage3** [comment]
@pstan26 @yknl I did have someone in the middle but then it seems more centralized to me. Decentralized should not have that large dot in the middle.

**Comment by pstan26** [comment]
cc;ing @shea256 for quick feedback so we don't spend too much more time deciding. My issue with the above version is it leaves it up to the imagination of the reader to infer that that is not some centralized hub instead of "you" at the middle. Only addt'l issues I'd bring up are whether we want to use real people.

Attaching the poor man's version of what I had in mind for the image (irrespective) of whether we use real people:
![screen shot 2018-01-24 at 6 00 06 pm](https://user-images.githubusercontent.com/5605552/35361900-1ea65c40-0131-11e8-8005-671e8bc22b9f.png)

**Comment by guylepage3** [comment]
Yes sir. Had a version like this in the sketch file. Looks good to go. 👍

**Comment by pstan26** [comment]
Awesome thank you, I just put a low-res image in there for the center as a stand in. Would you mind dropping in a hi-res version we can work with? Thank you very much

**Comment by guylepage3** [comment]
It's already there. I'll turn it on and export now. 😄

**Comment by pstan26** [comment]
Well thats easy! thanks!

**Comment by guylepage3** [comment]
![blog-multi-player-storage](https://user-images.githubusercontent.com/1711854/35362281-c7527ab2-0132-11e8-8e03-4d18112eb405.png)
